config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions'
  }
  
  post "/update_language", to: "application#set_locale", as: :set_locale

  scope '(:locale)', locale: /es|en/ do
    get 'privacy_policy', to: 'pages#privacy_policy', as: :privacy
    get 'terms_of_service', to: 'pages#terms_of_service', as: :terms

    unauthenticated :user do
      root to: "pages#home", as: :unauthenticated_root
    end

    get '/get-started', to: 'pages#home', as: :get_started

    resources :organizations, only: [:new, :create]

    authenticated :user do
      root to: 'passthrough#index', as: :authenticated_root
    end

    constraints SubdomainConstraint do
      get '/feedback', to: 'organizations#feedback', as: :feedback
      get '/boards', to: 'organizations#boards', as: :boards
      resources :organizations, only: [:edit, :update, :destroy]

      get '/members', to: 'organizations#members'
      patch '/remove_members/:user_id', to: 'organizations#remove_member', as: :remove_member

      resources :wishlists, except: :show do
        resources :integrations, only: [:new, :create]
        resources :wishes, only: [:new, :create, :index]
      end

      resources :wishes, only: [:create]

      resources :wishes, only: [:show, :edit, :update, :destroy] do
        resources :votes, only: [:create]
        resources :comments, only: [:create, :destroy, :edit, :update]
      end

      resources :votes, only: :destroy

      resources :integrations, only: :destroy
    end
  end
end

app/models/wish.rb
require_relative '../services/asana_api/asana_client'
class Wish < ApplicationRecord
  belongs_to :wishlist
  has_one :organization, through: :wishlist
  validates :title, presence: true
  has_many :votes, dependent: :destroy
  belongs_to :user
  has_rich_text :description
  has_many :comments, dependent: :destroy

  enum stage: { Backlog: 0, 'In process': 1, Launched: 3 }
  after_create :send_to_asana, if: :asana_integration?
  # after_create_commit { broadcast_append_to "wishes" }
  after_create :upvote

  include PgSearch::Model
  pg_search_scope :search_by_title_and_description,
                  against: %i[title],
                  associated_against: {
                    rich_text_description: %i[body]
                  },
                  using: {
                    tsearch: { prefix: true }
                  }

  pg_search_scope :search_by_board_name,
                  associated_against: {
                    wishlist: %i[title]
                  },
                  using: {
                    tsearch: { prefix: true }
                  }

  def user_vote(user)
    votes.find_by(user:)
  end

  def stage_color
    case stage.capitalize
    when "Backlog" then "#A0A0A0"
    when "In process" then "#F278F2"
    when "Launched" then "#2FC888"
    # when "Completed" then "#2FC888"
    # when "Archived" then "#ED9D02"
    end
  end

  # rubocop:enable Style/HashLikeCase
  def bg_stage_color
    case stage.capitalize
    when "Backlog" then "#EBEBEB"
    when "In process" then "#FAC7FA"
    when "Launched" then "#ACECD1"
    end
  end
  # rubocop:enable Style/HashLikeCase

  def self.filter_stages
    ["Backlog", "In process", "Launched"]
  end

  private

  def asana_integration?
    wishlist.integrations.find_by(name: "Asana").present?
  end

  def send_to_asana
    asana = wishlist.asana_integration
    AsanaApi::SendTask.new(asana.api_token).call(asana.workspace, asana.project, title, description.to_plain_text)
  end

  def upvote
    Vote.create!(wish: self, user:)
  end
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[show index] if :verify_private_wishlist
  after_action :verify_authorized
  before_action :order_column_whitelist,
                :order_direction_whitelist,
                :set_stages, only: :index

  def show
    @wish = Wish.find(params[:id])
    @wishlist = @wish.wishlist
    @comments = @wish.comments.order(created_at: :desc)
    @comment = Comment.new
    authorize @wish
    add_breadcrumb "Tickets", wishlist_wishes_path(@wishlist)
  end

  def new
    @wish = Wish.new
    @wishlist = Wishlist.find(params[:wishlist_id])
    authorize @wish
  end

  def index
    @wishlist = Wishlist.find(params[:wishlist_id])
    @wish = Wish.new
    authorize @wishlist
    @wishes = policy_scope(@wishlist.wishes)
    @wishes = Wishes::Filterer.new(filter_params:, scope: @wishes).call if params[:filter].present?

    add_breadcrumb "< Boards", wishlists_path
  end

  # rubocop:disable Metrics/MethodLength
  def create
    @wish = Wish.new(wish_params)
    @wish.user = current_user
    authorize @wish
    if @wish.save
      session[:wish_params] = nil
      flash[:notice] = "Ticket created successfully"
      redirect_to  request.referrer.include?("feedback") ? authenticated_root_path : wishlist_wishes_path(@wish.wishlist, anchor: "wish-#{@wish.id}")
    else
      flash[:alert] = "Ticket not created, try again later"
      redirect_to request.referrer
    end
  end
  # rubocop:enable Metrics/MethodLength

  def edit
    @wish = Wish.find(params[:id])
    @wishlist = @wish.wishlist
    authorize @wish
  end

  def update
    @wish = Wish.find(params[:id])
    authorize @wish
    if @wish.update(wish_params)
      flash[:notice] = "Ticket updated successfully, only you as a board owner can update the stage of a wish"
      redirect_to wish_path(@wish)
      create_comment if params[:wish][:stage].present?
    else
      flash[:alert] = "Ticket not updated, try again later"
      render "show", status: :unprocessable_entity
    end
  end

  def destroy
    @wish = Wish.find(params[:id])
    authorize @wish
    if @wish.destroy
      flash[:notice] = "Ticket deleted successfully"
      redirect_to request.referer
    else
      flash[:alert] = "Ticket not deleted, try again later"
      redirect_to request.referer
    end
  end

  def verify_private_wishlist
    @wishlist = Wishlist.find(params[:wishlist_id])
    @wishlist.private == false
  end

  private

  def order_column_whitelist
    @order_column_whitelist ||=
      Wishes::Filterer::ORDER_COLUMN_WHITELIST.map { [_1.titleize, _1] }
  end

  def create_comment
    Comment.create(user: current_user, wish: @wish, content: "The stage of this ticket has been updated to: #{@wish.stage}")
  end

  def order_direction_whitelist
    @order_direction_whitelist ||=
      Wishes::Filterer::ORDER_DIRECTION_WHITELIST.map { [_1.titleize, _1] }
  end

  def set_stages
    @stages = Wish.distinct.pluck(:stage)
  end

  def filter_params
    params[:filter].permit(:stage, :order_column, :order_direction)
  end

  def wish_params
    params.require(:wish).permit(:title, :description, :stage, :wishlist_id)
  end
end

app/views/wishes/_card.html.erb
<div class="card-product">
    <div class="card-product__info">
        <div class="card-product-infos">
            <h1><%= @wish.title %></h1>
            <small>Posted by <%= @wish.user.full_name %></small>
            <p><%= @wish.description %></p>
        </div>
    </div>
    <% if user_signed_in? && policy(@wish).edit? %>
        <div>
            <%= render "wishes/stage_form" %>
        </div>
    <% else %>
        <div class="card-product__status" style="background-color: <%= @wish.stage_color %>">
            <%= @wish.stage %>
        </div>
    <% end %>
</div>
<div class="card-product__icons">
    <div class="card-product__icon">
        <small><i class="fas fa-comment"></i> <%= @wish.comments.count %> comments</small>
    </div>
</div>
<% @comments.each do |comment| %>
    <div class="card-comment">
    <% if comment.user.photo_attached? %>
        <%= cl_image_tag comment.user.photo.key, alt: "#{comment.user.full_name} wyshlist profile photo", class: "avatar dropdown-toggle" %>
    <% else %>
        <%= image_tag "default-avatar.png", class: "avatar dropdown-toggle" %>
    <% end %>
        <div class="card-product-infos">
            <p><strong><%= comment.user.full_name %></strong><p>
            <% if comment.content.starts_with? "The stage of this ticket has been updated to:" %>
              <% wish = comment.content.split("The stage of this ticket has been updated to: ")[1] %>
              <p>The stage of this ticket has been updated to<span class="pill" style="background-color: <%= Wish.new(stage: wish).stage_color %>"><%= wish.downcase %></span></p>
            <% else %>
              <p><%= comment.content %></p>
            <% end %>
        </div>
    </div>
<% end %>

app/views/wishes/_feedback_filters.html.erb
<%= simple_form_for(:filter, url: authenticated_root_path, method: :get) do |f| %>
  <%= f.input :stage, collection: @stages, include_blank: true %>
  <%= f.input :wishlist_id, collection: @wishlists, include_blank: true %>
  <%= f.input :order_column, collection: @order_column_whitelist %>
  <%= f.input :order_direction, collection: @order_direction_whitelist %>
  <%= f.button :submit, 'Filter' %>
<% end %>

app/views/wishes/_filter.html.erb
<div data-controller="search-wishes">
  <div class="feedback-filter">
    <div class="filter">
      <% Wish.filter_stages.each do |stage| %>
        <%= filter_link(stage, :stage) %>
      <% end %>
    </div>
    <div class="sorting">
      <%# Sorting %>
      <div class="dropdown">
        <button class="p-0" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          <%= image_tag 'sort.png', alt: "sort-icon", class: ("active" if params[:order_column].present?) %>
        </button>
        <ul class="dropdown-menu">
          <li class="dropdown-header">SORT BY</li>
          <li><hr class="dropdown-divider"></li>
          <li class="dropdown-item"><%= sortable_link("Newest", "created_at", "DESC") %></li>
          <li class="dropdown-item"><%= sortable_link("Oldest", "created_at", "ASC") %></li>
          <li class="dropdown-item"><%= sortable_link("Votes", "votes_count", "DESC") %></li>
        </ul>
      </div>
      <%# Filter %>
      <div class="dropdown">
        <button class="p-0" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          <%= image_tag 'filter.png', alt: "filter-icon", class: ("active" if params[:board].present? || params[:start_date].present? || params[:end_date].present?) %>
          <% if params[:board].present? || params[:start_date].present? || params[:end_date].present? %>
            <div class="circle"></div>
          <% end %>
        </button>
        <ul class="dropdown-menu">
          <li class="dropdown-header">FILTER BY</li>
          <li><hr class="dropdown-divider"></li>
          <li class="dropdown-item">
            <%= link_to 'Date', '#', class: ("active" if params[:start_date].present? || params[:end_date].present?) %>
            <ul class="dropdown-menu dropdown-submenu">
              <%= form_with url: request.url, method: :get do |f| %>
                  <li class="dropdown-item flex-between">
                    <%= hidden_fields %>
                    <%= f.label :start_date, "From" %>
                    <%= f.date_field :start_date,
                                      class: "form-control",
                                      value: params[:start_date] %>
                  </li>
                  <li class="dropdown-item flex-between">
                    <%= hidden_fields %>
                    <%= f.label :end_date, "To" %>
                    <%= f.date_field :end_date,
                                      class: "form-control",
                                      value: params[:end_date] %>
                  </li>
                  <%= f.submit 'Filter', class:"d-none" %>
              <% end %>
            </ul>
          </li>
          <li class="dropdown-item">
            <%= link_to 'Board', '#', class: ("active" if params[:board].present?) %>
            <ul class="dropdown-menu dropdown-submenu">
              <%= form_with url: request.url, method: :get do |f| %>
                  <%= hidden_fields %>
                  <%= f.text_field :board,
                                  class: "dropdown-item form-control",
                                  placeholder: "Start typing...",
                                  value: params[:board] %>
              <% end %>
            </ul>
          </li>
          <li><hr class="dropdown-divider"></li>
          <li class="dropdown-item"><%= link_to "Clear all", request.path %></li>
        </ul>
      </div>
      <button class="p-0" type="button">
        <%= image_tag 'search.png', alt: "search-icon", data: { action: "click->search-wishes#search" } %>
      </button>
    </div>
  </div>
  <div class="search-bar d-none" data-search-wishes-target="form">
    <%= form_with url: request.url, method: :get, html: {class:
        ""} do |f| %>
        <%= hidden_fields %>
        <%= f.text_field :query,
                        class: "form-control",
                        placeholder: "Search...",
                        value: params[:query],
                        data: {search_wishes_target: "input"} %>
    <% end %>
  </div>
</div>

app/views/wishes/_form.html.erb
<%= simple_form_for [@wish], id: "add-wish" do |f| %>
    <%= f.input :wishlist_id, as: :hidden, input_html: { value: @wishlist.id } %>
    <%= f.input :title, label: false, input_html: { value: session["wish_params"]&.[]("title")}, placeholder: "Title" %>
    <%= f.rich_text_area :description, label: "Add a decription for this ticket", as: :text, placeholder: "i.e: At the moment our current solution is this, it would be great to have..." , value: (session["wish_params"]&.[]("description") unless session["wish_params"]&.[]("description") == false) %>
    <%= f.submit "Add a ticket", class: "btn-flat", data: { turbo: false }, style: "background-color: #{@wishlist&.organization&.color}" %>
<% end %>

app/views/wishes/_stage_form.html.erb
<div data-controller="wish-status-update" class="d-flex justify-content-between align-items-center">
    <%= simple_form_for @wish, html: {data: { wish_status_update_target: "form"}} do |f| %>
        <%= f.input :stage, 
                    collection: Wish.stages.keys,
                    as: :select, 
                    default: @wish.stage, 
                    label: false, 
                    class: "card-ghost card-ghost-wide card-product__status mb-0", 
                    style: "border-color: #{@wish.stage_color}; color: #{@wish.stage_color}",
                    prompt: "Stage of this feature", 
                    input_html: {
                        data: {
                                wish_status_update_target: "select",
                                confirm: "Are you sure you want to update the stage of this feature?",
                                action: "change->wish-status-update#update"
                        }
                    }
         %>
        <div class="modal fade" id="statusModal" tabindex="-1" aria-labelledby="statusModalLabel" aria-hidden="true">
            <div class="modal-dialog rounded">
                <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="statusModalLabel">Update status confirmation</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to update the status of this feature?</p>
                    <p>This update will appear in the activity feed of this feature.</p>
                    <%= f.submit "Confirm", class: "btn-flat" %>
                </div>
                </div>
            </div>
        </div>
            
    <% end %>
</div>

app/views/wishes/_ticket.html.erb
<div class="card-wish wrapper-container"
    data-action="click->ticket-popup#show click->ticket-popup#active">
  <div class="d-flex justify-content-between align-items-start">
    <%= link_to wish_path(wish, source: 'feedback'), data: {turbo_frame: "wish-view"}, style: "flex-grow: 1" do %>
      <div>
        <p><strong><%= wish.title %></strong></p>
        <%= wish.description.to_plain_text.truncate(150) %>
        <ul class='list-inline'>
          <li class="list-inline-item"><%= image_tag 'star.png', alt: "text" %> <%= wish.votes_count %></li>
          <li class="list-inline-item"><%= image_tag 'message-square.png', alt: "text" %> <%= wish.comments.count %></li>
        </ul>
      </div>
    <% end %>
    <div class="">
      <% if policy(wish).edit? %>
        <%= link_to edit_wish_path(wish) do %>
          <%= image_tag 'edit.png', class: "icon-small me-3", alt: "edit" %>
        <% end %>
      <% end %>
      <% if policy(wish).destroy? %>
        <%= link_to wish_path(wish), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
          <%= image_tag 'trash.png', class: "icon-small", alt: "delete" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/wishes/_user_filters.html.erb
<%= simple_form_for(:filter, url: wishlist_wishes_path(@wishlist), method: :get) do |f| %>
  <%= f.input :stage, collection: @stages, include_blank: true %>
  <%= f.input :order_column, collection: @order_column_whitelist %>
  <%= f.input :order_direction, collection: @order_direction_whitelist %>
  <%= f.button :submit, 'Filter' %>
<% end %>

app/views/wishes/_wishes.html.erb
<% @wishes.each do |wish| %>
  <%= link_to wish_path(wish), class: "card-product__link flex-grow-1" do %>
    <div class="card-product" id="wish-<%= wish.id %>">
      <div class="card-product__info">
        <div class="card-product-infos">
          <h2><%= wish.title %></h2>
          <div class="card-product__icon">
            <small>Posted by  <%= wish.user.full_name %></small>
          </div>
          <%= wish.description.to_plain_text.truncate(150) %>
          <div class="card-product__icons">
            <div class="card-product__icon me-2">
              <div class="card-ghost card-ghost-wide card-product__status" style="border-color: <%= wish.stage_color %>; color: <%= wish.stage_color %>">
                <%= wish.stage %>
              </div>
            </div>
            <div class="card-product__icon">
              <small><i class="fas fa-comment"></i> <%= wish.comments.count %> comments</small>
            </div>
          </div>
        </div>
      </div>
      <div class="card-product__votes">
        <div class="card-product__vote-count"><%= wish.votes.count %> <small>votes</small></div>
        <% if wish.user_vote(current_user) %>
          <%= link_to "downvote", vote_path(wish.user_vote(current_user)), data: { turbo_method: "delete" }, class: "upvote-button", id: "downvote" %>
        <% else %>
          <%= link_to "Upvote", wish_votes_path(wish), data: { turbo_method: "post" }, class: "upvote-button", id: "upvote" %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/wishes/edit.html.erb
<div class="my-container">
    <%= link_to "< Back", :back %>
    <div class="card-product form-wrapper">
        <h1>Edit this idea</h1>
        <%= render "form" %>
        <%= link_to "Delete this idea", wish_path(@wish), data: {turbo_method: "delete", turbo_confirm: "Are you sure?"}, id: "delete-idea" %>
    </div>
</div>

app/views/wishes/index.html.erb
<% content_for :meta_title, "#{@wishlist.title} | Wyshlist" %>
<% content_for :meta_description, @wishlist.description %>
<div class="my-container">
    <div class="title-header">
        <div class="title-wrapper">
            <h1><%= @wishlist.title %></h1>
            <br>
            <small class="title-header__description"><%= @wishlist.description %></small>
        </div>
        <div>
            <% if user_signed_in? && (current_user.team_member? || current_user.super_team_member?) %>
                <%= link_to edit_wishlist_path(@wishlist) do %>
                    <div class="card-product__edit">
                        <%= t('wishlist_page.edit_board') %> <i class="fa-solid fa-pencil"></i>
                    </div>
                <% end %>
            <% end %>
        </div>
    </div>
    <div class="cards-columns">
        <div class="wishes-filter">
            <ul class="wishes-filter__list">
                <h4><%= t('wishlist_page.add_new_ticket') %></h4>
                <br>
                <div class="new-wish-wrapper new-wish-sidebar-wrapper">
                <%= render "form", wish: @wish, wishlist: @wishlist %>
                </div>
                <br>
                <div data-controller="clipboard" data-clipboard-feedback-text-value="<%= t('wishlist_page.copied') %>" class="wishes__copy">
                    <input type="text" value="<%= request.url %>" data-clipboard-target="source" class="wishes__copy-link" />
                    <button type="button" data-action="clipboard#copy" data-clipboard-target="button">
                        <%= image_tag "clipboard.png", class: "wishes__clipboard"%>
                    </button>
                </div>
                <br>

                <small> <%= t('wishlist_page.powered_by') %></small>
            </ul>
        </div>
        <div class="wishes-wrapper">
            <%= render "filter" %>
            <br>
            <% if @wishes.any? %>
                <%= render "wishes/wishes", wishes: @wishes %>
            <% elsif params[:stage] %>
                <div class="no-wishes">
                    <h2> <%= t('wishlist_page.no_contributions_stage') %> </h2>
                    <p> <%= t('wishlist_page.stay_tuned') %> </p>
                </div>
            <% else %>
                <div class="no-wishes">
                    <h2> <%= t('wishlist_page.no_ideas_yet') %> </h2>
                    <p> <%= t('wishlist_page.be_first_add') %> </p>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/wishes/new.html.erb
<%= turbo_frame_tag "new-wish" do %>
    <%= render "form", wish: @wish, wishlist: @wishlist %>
<% end %>

app/views/wishes/show.html.erb
<% content_for :meta_title, "#{@wish.title} | Wyshlist" %>
<% content_for :meta_description, @wish.description %>
<div class="my-container fix-page-wrapper">
  <%= turbo_frame_tag "wish-view", class: "flex-grow-1 d-flex flex-column" do %>
    <% if params[:source] == 'feedback' %>
      <%= link_to t('wish_details.back'), '#', class: "d-inline-block d-lg-none", data: {action: "click->ticket-popup#hide"} %>
    <% else %>
      <%= link_to t('wish_details.back'), wishlist_wishes_path(@wish.wishlist), class: "d-inline-block", data: { turbo_frame: :_top } %>
    <% end %>

    <div class="card-show-wish mt-2">
      <div class="card-header">
        <div class="flex-between mb-3">
          <div class="flex-between">
            <% if @wish.user.photo.attached? %>
              <%= cl_image_tag @wish.user.photo.key, class: "avatar-small" %>
            <% else %>
              <div class="avatar-small avatar-name">
                <%= @wish.user.initial %>
              </div>
            <% end %>
            <small class="ms-2 user-name"><%= @wish.user.full_name %></small>
          </div>
          <div class="flex-between">
            <div class="card-ghost me-2">
              <span class="me-1"><%= @wish.votes.count %></span>
              <%= image_tag "carrot-up.png", width: '12px', alt: t('wish_details.votes_icon_alt') %>
            </div>
            <% if user_signed_in? && policy(@wish).update? %>
              <%= render "wishes/stage_form" %>
            <% else %>
              <div class="card-ghost card-ghost-wide card-product__status" style="border-color: <%= @wish.stage_color %>; color: <%= @wish.stage_color %>">
                  <%= @wish.stage %>
              </div>
            <% end %>
          </div>
        </div>

        <div class="flex-between">
          <h1><%= @wish.title %></h1>
        </div>
        <p><%= @wish.description %></p>
      </div>
      <div class="card-comments">
        <h4 class="my-4"><%= t('wish_details.activity') %></h4>
        <div class="comments">
          <% @comments.each do |comment| %>
              <div class="card-comment <%= 'border-bottom card-border-color' unless comment == @comments.last %>">
                <div class="flex-start mb-2">
                  <% if comment.user.photo.attached? %>
                    <%= cl_image_tag comment.user.photo.key, class: "avatar-small" %>
                  <% else %>
                    <div class="avatar-small avatar-name">
                      <%= comment.user.initial %>
                    </div>
                  <% end %>
                  <small class="ms-2 user-name"><%= comment.user.full_name %></small>
                  <% if comment.from_team?(@wishlist.organization) %>
                    <small class="ms-2 staff-pill"><%= comment.user.organization.name %></small>
                  <% end %>
                </div>
                <p><%= comment.content %></p>
                <ul class='list-inline'>
                  <li class="list-inline-item"><small><%= comment.created_at.strftime('%B %e, %Y') %></small></li>
                </ul>
              </div>
          <% end %>
        </div>
      </div>
      <div class="form-comment">
        <div class="divider"></div>
        <%= simple_form_for [@wish, @comment], defaults: { wrapper: false }, html: { class: "my-3", data: { controller: "add-comment" }} do |f| %>
          <div class="flex-between form-comment__input">
            <% if current_user&.photo_attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar" %>
            <% else %>
              <div class="avatar avatar-name">
                <%= current_user&.initial %>
              </div>
            <% end %>
            <%= f.input :content,
                        label: false,
                        placeholder: t('wish_details.leave_comment_placeholder'),
                        input_html: {
                          data: {
                            action: "
                              focus->add-comment#showButton
                              blur->add-comment#hideButton
                              keyup->add-comment#activateButton
                            "
                          }
                        } %>
          </div>
          <%= f.button :submit, t('wish_details.submit_button'), class: "btn-flat px-4 py-2 mb-0 d-none", disabled: true, data: { add_comment_target: "button" } %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>