config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions'
  }
  
  post "/update_language", to: "application#set_locale", as: :set_locale

  scope '(:locale)', locale: /es|en/ do
    get 'privacy_policy', to: 'pages#privacy_policy', as: :privacy
    get 'terms_of_service', to: 'pages#terms_of_service', as: :terms

    unauthenticated :user do
      root to: "pages#home", as: :unauthenticated_root
    end

    get '/get-started', to: 'pages#home', as: :get_started

    resources :organizations, only: [:new, :create]

    authenticated :user do
      root to: 'passthrough#index', as: :authenticated_root
    end

    constraints SubdomainConstraint do
      get '/feedback', to: 'organizations#feedback', as: :feedback
      get '/boards', to: 'organizations#boards', as: :boards
      resources :organizations, only: [:edit, :update, :destroy]

      get '/members', to: 'organizations#members'
      patch '/remove_members/:user_id', to: 'organizations#remove_member', as: :remove_member

      resources :wishlists, except: :show do
        resources :integrations, only: [:new, :create]
        resources :wishes, only: [:new, :create, :index]
      end

      resources :wishes, only: [:create]

      resources :wishes, only: [:show, :edit, :update, :destroy] do
        resources :votes, only: [:create]
        resources :comments, only: [:create, :destroy, :edit, :update]
      end

      resources :votes, only: :destroy

      resources :integrations, only: :destroy
    end
  end
end

app/views/shared/_announcement_navbar.html.erb
<div class="announcement-bar">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <p class="announcement-bar-text">📣 Announcing: lifetime free features for all beta users subscribed before 09/2023</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_dashboard_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon border-bottom">
  <div class="container-fluid justify-content-between justify-content-lg-end">
    <%= link_to user_signed_in? ? authenticated_root_path : unauthenticated_root_path, class: "navbar-brand d-block d-lg-none" do %>
      <%= image_tag "logo-short.png", class: "logo"%>
    <% end %>
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <% if current_user.has_an_organization? %>
          <%= render 'shared/nav_links', type: 'navbar' %>
          <div class="dropdown nav-item">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <div class="avatar flex-center avatar-name" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup=true aria-expanded=false >
                <%= current_user.initial %>
              </div>
            <% end %>
            <ul class="dropdown-menu position-absolute dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= render 'shared/nav_links', type: 'dropdown' %>
              <%= link_to t('dashboard_navbar.edit_my_account'), edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to t('dashboard_navbar.log_out'), destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              <%= render 'shared/sidebar_links', type: 'dropdown' %>
            </ul>
          </div>
        <% end %>
      <% else %>
        <li class="nav-item">
          <%= link_to t('dashboard_navbar.log_in'), new_user_session_path, class: "ghost-button" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
      <%= link_to t('footer.privacy_policy'), privacy_path, class: "primary-link" %>
      |
      <%= link_to t('footer.terms_of_service'), terms_path, class: "primary-link" %>
    <div class="footer-links">
      <% if Wishlist.admin_wishlists.any? %>
        <%= link_to t('footer.contribute'), wishlist_wishes_path(Wishlist.admin_wishlists.first), class: "main-link" %>
      <% end %>
      <%= t('footer.copy_right', year: 2023) %>
    </div>
  </div>
</div>

app/views/shared/_locale_form.html.erb
<%= form_tag set_locale_path, class: "language-pill" do %>
    <%= select_tag :locale, options_for_select([["🇬🇧 EN", :en], ["🇪🇸 ES", :es]], I18n.locale), :onchange => "this.form.submit();", style: "border: none; padding: 0px 5px; border-radius: 10px; border: 1px solid #ddd;"  %>
<% end %>

app/views/shared/_nav_links.html.erb
<% item_class = type == 'navbar' ? 'nav-item d-none d-lg-flex' : 'dropdown-item d-flex d-lg-none' %>

<li class="<%= item_class %>">
  <%= link_to "Feedbacks", feedback_path, class: "#{'nav-link' if type == 'navbar'}" %>
</li>
<li class="<%= item_class %>">
  <%= link_to boards_path, class: "#{'nav-link' if type == 'navbar'} px-0" do %>
    Boards
  <% end %>
</li>
<li class="<%= item_class %>">
  <%= link_to wishlists_path, target: "_blank", class: "#{'nav-link' if type == 'navbar'} px-0" do %>
    <% if type == 'navbar' %>
      <%= image_tag 'eye.png', class: "icon", alt: "public view" %>
    <% else %>
      Public View
    <% end %>
  <% end %>
</li>
<li class="<%= item_class %> d-none">
  <%# To uncomment when notifications feature liveg %>
  <% link_to '#', target: "_blank", class: "#{'nav-link' if type == 'navbar'} px-0" do %>
    <%= image_tag 'bell.png', class: "icon", alt: "notification" %>
  <% end %>
</li>

app/views/shared/_navbar.html.erb
<%#= render "shared/announcement_navbar" %>
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon border-bottom">
  <div class="container-fluid justify-content-end">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <% if current_user.has_an_organization? %>
          <li class="nav-item">
            <%= link_to wishlists_path(team_view: true), class: "nav-link px-0" do %>
              All Wishlists
              <%#= image_tag 'eye.png', class: "icon", alt: "public view" %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to wishlists_path, target: "_blank", class: "nav-link px-0" do %>
              <%= image_tag 'eye.png', class: "icon", alt: "public view" %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to '#', target: "_blank", class: "nav-link px-0" do %>
              <%= image_tag 'bell.png', class: "icon", alt: "notification" %>
            <% end %>
          </li>
          <div class="dropdown nav-item">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <div class="avatar flex-center avatar-name" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup=true aria-expanded=false >
                <%= current_user.initial %>
              </div>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Edit my account", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </div>
        <% end %>
      <% else %>
        <li class="nav-item">
          <%= link_to "Log in", new_user_session_path, class: "ghost-button" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_pages_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon border-bottom">
    <%= link_to authenticated_root_path do %>
        <%= image_tag 'logo.jpg', class: "logo" %>
    <% end %>
    <div class="container-fluid justify-content-end">
        <ul class="navbar-nav">
            <% if user_signed_in? %>
                <% if current_user.has_an_organization? %>
                    <li class="nav-item">
                        <%= link_to t('pages_navbar.public_preview'), wishlists_url(subdomain: current_user.organization.subdomain), target: "_blank", class: "ghost-button nav-link" %>
                    </li>
                <% end %>
                <li class="nav-item">
                    <%= link_to t('pages_navbar.log_out'), destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
                </li>
            <% else %>
                <li class="nav-item">
                    <%= link_to t('pages_navbar.log_in'), new_user_session_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to t('pages_navbar.create_account'), new_user_registration_path, class: "ghost-button nav-link" %>
                </li>
            <% end %>
        </ul>
    </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="sidebar d-none d-lg-flex">
  <%= link_to user_signed_in? ? authenticated_root_path : unauthenticated_root_path, class: "navbar-brand" do %>
    <%= image_tag "logo-short.png", class: "logo"%>
  <% end %>
  <div class="dropdown">
    <%= image_tag "setting.png", class: "icon dropdown-toggle", id: "sidebarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="sidebarDropdown">
      <%= render 'shared/sidebar_links', type: 'sidebar' %>
    </div>
  </div>
</div>

app/views/shared/_sidebar_links.html.erb
<% item_class = type == 'sidebar' ? 'd-none d-lg-flex' : 'd-flex d-lg-none' %>

<li><hr class="dropdown-divider d-lg-none"></li>

<% if Wishlist.admin_wishlists.any? %>
  <%= link_to "Contribute to Wyshlist", wishlist_wishes_url( Wishlist.admin_wishlists.first, subdomain: "wyshlist"), class: "dropdown-item #{item_class} main-link" %>
<% end %>
<% if current_user.organization.present? && policy(current_user.organization).edit? %>
  <%= link_to current_user.organization.name, edit_organization_path(current_user.organization), class: "dropdown-item #{item_class}" %>
<% end %>
<%= link_to "Team members", members_path, class: "dropdown-item #{item_class}"  %>

app/views/shared/_user_navbar.html.erb
<div class="my-container">
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
        <div class="container-fluid">
            <% if @current_organization %>
                <%= link_to wishlists_url(subdomain: @current_organization.subdomain), class: "navbar-brand" do %>
                    <% if @current_organization.logo.attached? %>
                        <%= cl_image_tag @current_organization.logo.key, class: "logo" %>
                    <% else %>
                        <%= image_tag 'logo.jpg', class: "logo" %>
                    <% end %>
                <% end %>
            <% end %>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="<%= t('navbar.toggle_navigation') %>">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto">
                    <% if @wishlist %>
                        <li class="nav-item">
                            <%= form_tag wishlist_wishes_path(@wishlist), method: :get do %>
                                <div class="tickets-searchbar">
                                    <%= text_field_tag :query, params[:query], placeholder: t('navbar.search_placeholder'), class: "tickets-searchbar__input form-control" %>
                                    <% submit_tag t('navbar.search'), class: "tickets-searchbar__button" %>
                                </div>
                            <% end %>
                        </li>
                    <% end %>
                    <li class="nav-item active">
                        <%= link_to t('navbar.explore'), wishlists_url(subdomain: @current_organization.subdomain), class: "nav-link" %>
                    </li>
                    <li class="nav-item dropdown">
                        <%= link_to t('navbar.give_feedback'), "#", class: "nav-link dropdown-toggle", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                            <% @current_organization.wishlists.each do |wishlist| %>
                                <%= link_to wishlist.title.truncate(20), wishlist_wishes_path(wishlist), class: "dropdown-item" %>
                            <% end %>
                        </div>
                    </li>
                    <% if !user_signed_in? %>
                        <li class="nav-item">
                            <%= link_to t('navbar.log_in'), new_user_session_path, class: "ghost-black" %>
                        </li>
                    <% end %>
                    <% if User.has_valid_organization_member?(current_user) %>
                        <li class="nav-item">
                            <%= link_to t('navbar.new_board'), new_wishlist_path, class: "nav-link mx-auto link " %>
                        </li>
                        <li class="nav-item align-items-center d-flex">
                            <%= link_to t('navbar.dashboard'), authenticated_root_path, class: "upvote-button mx-auto" %>
                        </li>
                    <% end %>

                    <% if user_signed_in? %>
                      <div class="dropdown nav-item">
                        <% if current_user.photo.attached? %>
                          <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                        <% else %>
                          <div class="avatar flex-center avatar-name" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup=true aria-expanded=false >
                            <%= current_user.initial %>
                          </div>
                        <% end %>
                        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                          <%= link_to t('navbar.edit_my_account'), edit_user_registration_path, class: "dropdown-item" %>
                          <%= link_to t('navbar.log_out'), destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
                        </div>
                      </div>
                    <% end %>

                </ul>
            </div>
        </div>
    </div>
</div>