config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions'
  }
  
  post "/update_language", to: "application#set_locale", as: :set_locale

  scope '(:locale)', locale: /es|en/ do
    get 'privacy_policy', to: 'pages#privacy_policy', as: :privacy
    get 'terms_of_service', to: 'pages#terms_of_service', as: :terms

    unauthenticated :user do
      root to: "pages#home", as: :unauthenticated_root
    end

    get '/get-started', to: 'pages#home', as: :get_started

    resources :organizations, only: [:new, :create]

    authenticated :user do
      root to: 'passthrough#index', as: :authenticated_root
    end

    constraints SubdomainConstraint do
      get '/feedback', to: 'organizations#feedback', as: :feedback
      get '/boards', to: 'organizations#boards', as: :boards
      resources :organizations, only: [:edit, :update, :destroy]

      get '/members', to: 'organizations#members'
      patch '/remove_members/:user_id', to: 'organizations#remove_member', as: :remove_member

      resources :wishlists, except: :show do
        resources :integrations, only: [:new, :create]
        resources :wishes, only: [:new, :create, :index]
      end

      resources :wishes, only: [:create]

      resources :wishes, only: [:show, :edit, :update, :destroy] do
        resources :votes, only: [:create]
        resources :comments, only: [:create, :destroy, :edit, :update]
      end

      resources :votes, only: :destroy

      resources :integrations, only: :destroy
    end
  end
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :users, dependent: :destroy
  has_many :wishlists, dependent: :destroy
  has_many :wishes, through: :wishlists
  validates :name, presence: true, uniqueness: true
  validates :subdomain, presence: true, uniqueness: true, format: { with: /\A[\w\-]+\z/ }
  before_save :titleize_name
  after_create :create_subdomain
  after_destroy :delete_subdomain
  has_one_attached :logo

  def titleize_name
    self.name = name.titleize
  end

  def organization_owner?(user)
    users.first == user
  end

  def organization_member?(user)
    users.include?(user)
  end

  private

  def delete_subdomain
    HerokuApi::SubdomainDeletor.new(subdomain).call if Rails.env.production?
  end

  def create_subdomain
    HerokuApi::SubdomainCreator.new(subdomain).call if Rails.env.production?
  end
end

app/controllers/organizations_controller.rb
# rubocop:disable Metrics/ClassLength
class OrganizationsController < ApplicationController
  before_action :set_organization, only: %i[show edit update destroy]
  before_action :check_team_member_subdomain, only: %i[feedback boards members edit]
  before_action :order_column_whitelist,
                :order_direction_whitelist,
                :set_stages,
                :set_wishlists, only: :feedback

  def new
    @organization = Organization.new
    @organization_search = ""
    authorize @organization
  end

  def show
    @wishlists = @organization.wishlists.sort { |a, b| b.wishes.count <=> a.wishes.count }
    @wishlist = @organization.wishlists.first
    authorize @organization
  end

  # rubocop:disable Metrics/MethodLength
  def create
    if params[:organization_search] && params[:organization_search] != ""
      handle_existing_organization(params[:organization_search])
    else
      @organization = Organization.new(organization_params)
      authorize @organization
      respond_to do |format|
        if @organization.save
          HerokuApi::SubdomainCreator.new(@organization.subdomain).call if Rails.env.production?
          current_user.update(organization: @organization, role: 'super_team_member', super_team_member_since: Time.now)
          format.html { update_user_and_redirect(@organization) }
        else
          format.html { render :new, status: :unprocessable_entity }
        end
        format.json
      end
    end
  end
  # rubocop:enable Metrics/MethodLength

  def edit
    authorize @organization
  end

  def update
    authorize @organization
    if @organization.update(organization_params)
      flash[:notice] = "Organization updated successfully"
      redirect_to authenticated_root_url(subdomain: @organization.subdomain), allow_other_host: true
    else
      flash[:alert] = "Organization not updated, try again later"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @organization
    if @organization.destroy && current_user.update(organization: nil, role: 'user')
      flash[:notice] = "Organization deleted successfully"
    else
      flash[:alert] = "Organization not deleted, try again later"
      render :edit, status: :unprocessable_entity
    end
    redirect_to authenticated_root_path
  end

  def feedback
    @organization = @current_organization
    @wishlists = @organization.wishlists
    authorize @organization
    @wish = Wish.new
    @wishes = @organization.wishes
    @wishes = Wishes::FeedbackFilterer.new(filter_params: params, scope: @wishes).call
  end

  def boards
    @organization = @current_organization
    @wishlists = @organization.wishlists
    authorize @organization
  end

  def members
    @organization = Organization.find_by(subdomain: request.subdomain)
    authorize @organization
    @members = @organization.users.order(:first_name)
  end

  def remove_member
    @organization = Organization.find_by(subdomain: request.subdomain)
    authorize @organization
    @member = User.find(params[:user_id])
    @member.update(organization: nil, role: 'user')
    redirect_to members_path
    flash[:notice] = "#{@member.email} has been removed from organization"
  end

  private

  def order_column_whitelist
    @order_column_whitelist ||=
      Wishes::FeedbackFilterer::ORDER_COLUMN_WHITELIST.map { [_1.titleize, _1] }
  end

  def set_wishlists
    @wishlists = @current_organization.wishlists
  end

  def check_team_member_subdomain
    if current_user.organization.nil?
      redirect_to new_organization_path
    elsif request.subdomain != current_user.organization.subdomain
      redirect_to authenticated_root_url(subdomain: current_user.organization.subdomain), allow_other_host: true
    end
  end

  def set_organization
    @organization = Organization.find(params[:id]) if params[:id]
    @organization = Organization.find_by(subdomain: request.subdomain)
    authorize @organization
  end

  def organization_params
    params.require(:organization).permit(:name, :logo, :color, :subdomain)
  end

  def order_direction_whitelist
    @order_direction_whitelist ||=
      Wishes::FeedbackFilterer::ORDER_DIRECTION_WHITELIST.map { [_1.titleize, _1] }
  end

  def set_stages
    @stages = Wish.distinct.pluck(:stage)
  end

  def filter_params
    params[:filter].permit(:stage, :wishlist_id, :order_column, :order_direction)
  end

  def handle_existing_organization(organization_name)
    organization_name_downcase = organization_name.downcase
    @organization = Organization.where('LOWER(name) ILIKE ?', organization_name_downcase).first ||
                    Organization.new
    authorize @organization
    if @organization.id
      update_user_and_redirect(@organization)
    else
      redirect_to new_organization_path, alert: "Team not found, maybe you should create it?"
    end
  end

  def update_user_and_redirect(organization)
    current_user.update(organization: organization, role: 'super_team_member', super_team_member_since: Time.now)
    redirect_to authenticated_root_url(subdomain: current_user.organization.subdomain), allow_other_host: true
  end
end
# rubocop:enable Metrics/ClassLength

app/views/organizations/_form.html.erb
<%= simple_form_for @organization, html: {data: {controller: "photo-preview", action: "submit->loading-organization#loading", loading_organization_target:"form"}} do |f| %>
    <%= image_tag "", class: "hidden avatar-x-large", data: { photo_preview_target: "preview" } %>
    <%= f.input :logo, as: :file, input_html: { class: 'd-none', data: { photo_preview_target: "input", action:"change->photo-preview#displayPreview" }}, label_html: { class: 'upload-photo'}, label: '📷 Upload a logo for your team'%>
    <%= f.input :name, required: true, label: "Create your team", placeholder: "ie: My Company", name: "name"  %>
    <label class="form-label string required" for="subdomain_name">Choose your subdomain<abbr title="required">*</abbr></label>
    <div class="subdomain-input-wrapper">
        <% if params[:action] == "edit" %>
            <%= f.input :subdomain, required: true, label: false, placeholder: "ie: mycompany", name: "subdomain",  input_html: { disabled: true, value: @organization.subdomain } %>
        <% else %>
            <%= f.input :subdomain, required: true, label: false, placeholder: "ie: mycompany", name: "subdomain" %>
        <% end %>
        <small>.wyshlist.net<small>
    </div>
    <%= f.input :color,
        as: :color,
        label: "Choose a brand color",
        placeholder: "Color",
        input_html: { class: "color-input #{'color-center' if params[:action] == 'new'}" }
    %>
    <%= f.submit "Submit", class: "btn-flat"%>
<% end %>
<br>
<% if params[:action] == "edit" %> 
    <%= link_to "Delete organziation", organization_path(@organization), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete your team? Your team, boards and customer's tickets will also be deleted forever 🤯" }, class: "delete-link" %>
<% end %>

app/views/organizations/_organization_search.html.erb
<%= form_tag organizations_path, method: "post", class: "form-search" do |f| %>
    <%= label_tag(:organization_search, "Search for your team") %>
    <%= text_field_tag :organization_search, nil, class: "form-control" %>
    <br>
    <%= submit_tag "Search", class: "btn-flat" %>
<% end %>

app/views/organizations/_wish_ticket.html.erb
<%= link_to wish_path(wish), data: {turbo_frame: "wish-view"} do %>
  <div class="card-wish wrapper-container">
    <p><strong><%= wish.title %></strong></p>
    <%= wish.description %>
    <ul class='list-inline'>
      <li class="list-inline-item"><%= image_tag 'star.png', alt: "text" %> <%= wish.votes.count %></li>
      <li class="list-inline-item"><%= image_tag 'message-square.png', alt: "text" %> <%= wish.comments.count %></li>
    </ul>
  </div>
<% end %>

app/views/organizations/boards.html.erb
<div class="my-container">
  <div class="title-header align-items-center">
    <h1><%= t("boards") %></h1>
    <% if user_signed_in? && (current_user.team_member? || current_user.super_team_member?) %>
      <%= link_to new_wishlist_path, class: 'ghost-button' do %>
        <i class="fa-solid fa-plus"></i>
      <% end %>
    <% end %>
  </div>
  <%= render "wishlists/wishlists_cards", wishlists: @wishlists  %>
</div>

app/views/organizations/edit.html.erb
<div class="my-container">
    <h1>Edit your team details</h1>
    <%= render "form" %>
</div>

app/views/organizations/feedback.html.erb
<div class="feedback-wrapper" data-controller="ticket-popup">
  <div class="feedback__column-left">
    <div class="wrapper-container">
      <div class="d-flex justify-content-between align-items-start mb-3">
        <h2><%= t('tickets.title') %></h2>
        <button type="button" class="ghost-button" data-bs-toggle="modal" data-bs-target="#exampleModal">
          <i class="fa-solid fa-plus"></i>
        </button>
      </div>
      <%= render "wishes/filter" %>
    </div>
    <div class="tickets">
      <% if @wishes.empty? %>
        <div class="wrapper-container border-0">
          <small><%= t('tickets.no_tickets') %></small>
        </div>
      <% end %>
      <% @wishes.each do |wish| %>
        <%= render 'wishes/ticket', wish: wish %>
      <% end %>
    </div>
  </div>
  <div class="feedback__column-right d-none d-lg-block <%= 'flex-center' if @wishes.empty? %>" data-ticket-popup-target="popup">
    <% if @wishlists.empty? %>
      <%= link_to t('tickets.create_board'), new_wishlist_path, class: "btn-flat" %>
    <% elsif @wishes.empty? %>
      <!-- Button trigger modal -->
      <button type="button" class="btn-flat" data-bs-toggle="modal" data-bs-target="#exampleModal">
        <%= t('tickets.create_ticket') %>
      </button>
      <!-- Modal -->
    <% else %>
      <div class="wrapper-container pb-0 h-100">
        <%= turbo_frame_tag "wish-view", src: wish_path(@wishes.first, source: 'feedback'), class: "h-100 flex-grow-1 d-flex flex-column" %>
      </div>
    <% end %>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog rounded">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel"><%= t('tickets.add_new_ticket') %></h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <%= simple_form_for @wish do |f| %>
              <%= f.association :wishlist, collection: @wishlists, label: false, placeholder: t('tickets.title_placeholder') %>
              <%= f.input :title, label: false, placeholder: t('tickets.title_placeholder') %>
              <%= f.rich_text_area :description, label: t('tickets.description_label'), placeholder: t('tickets.description_placeholder'), as: :text %>
              <%= f.submit t('tickets.add_ticket_button'), class: "btn-flat", data: { turbo: false }%>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/organizations/members.html.erb
<div class="my-container">
  <div class="d-flex justify-content-between mt-4">
    <h1>Members</h1>
    <% if policy(@organization).remove_member? %>
      <%= link_to "Invite Member", new_user_invitation_path, class: "btn-flat" %>
    <% end %>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Email</th>
        <th scope="col">Role</th>
        <th scope="col">Invitation Status</th>
        <% if policy(@organization).remove_member? %>
          <th scope="col"></th>
          <%# <th scope="col"></th> %>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @members.each_with_index do |member, index| %>
        <tr>
          <th scope="row"><%= index + 1 %></th>
          <td><%= member.first_name %></td>
          <td><%= member.last_name %></td>
          <td><%= member.email %></td>
          <td><%= member.role %></td>
          <td><%= member.invitation_status %></td>
          <% if policy(@organization).remove_member? %>
            <td>
              <%= link_to remove_member_path(member), data: { turbo_method: 'patch' }, class: "text-dark" do %>
                <i class="fa-solid fa-trash"></i>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/organizations/new.html.erb
<div class="my-container full-screen d-flex align-items-center position-relative" data-controller="loading-organization">
  <div class="card-product form-wrapper flex-grow-1">
    <h1><%= t('create_team.title') %></h1>
    <p><%= t('create_team.description') %></p>
    <div class="tab-content" id="pills-tabContent">
      <div class="tab-pane fade show active" id="pills-create" role="tabpanel" aria-labelledby="pills-create-tab" tabindex="0">
        <%= render "form" %>
      </div>
    </div>
  </div>

  <div class="loading-page d-none" data-loading-organization-target="loader">
    <div class="spinner"></div>
  </div>
</div>

app/views/organizations/show.html.erb
<div class="my-container">
    <div class="title-header">
        <h1>
          <%=  @organization.name  %> boards
        </h1>
    </div>
    <div class="breadcrumbs-wrapper">
        <small><%= render_breadcrumbs :separator => "  /  " %></small>
    </div>
    <% if @wishlists.any? %>
        <%= render "wishlists/wishlists_cards", wishlists: @wishlists  %>
    <% else %>
        <div class="card-product">
            <p>There are no boards yet.</p>
            <p>Click on the button above to create one.</p>
        </div>
    <% end %>
</div>