config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions'
  }
  
  post "/update_language", to: "application#set_locale", as: :set_locale

  scope '(:locale)', locale: /es|en/ do
    get 'privacy_policy', to: 'pages#privacy_policy', as: :privacy
    get 'terms_of_service', to: 'pages#terms_of_service', as: :terms

    unauthenticated :user do
      root to: "pages#home", as: :unauthenticated_root
    end

    get '/get-started', to: 'pages#home', as: :get_started

    resources :organizations, only: [:new, :create]

    authenticated :user do
      root to: 'passthrough#index', as: :authenticated_root
    end

    constraints SubdomainConstraint do
      get '/feedback', to: 'organizations#feedback', as: :feedback
      get '/boards', to: 'organizations#boards', as: :boards
      resources :organizations, only: [:edit, :update, :destroy]

      get '/members', to: 'organizations#members'
      patch '/remove_members/:user_id', to: 'organizations#remove_member', as: :remove_member

      resources :wishlists, except: :show do
        resources :integrations, only: [:new, :create]
        resources :wishes, only: [:new, :create, :index]
      end

      resources :wishes, only: [:create]

      resources :wishes, only: [:show, :edit, :update, :destroy] do
        resources :votes, only: [:create]
        resources :comments, only: [:create, :destroy, :edit, :update]
      end

      resources :votes, only: :destroy

      resources :integrations, only: :destroy
    end
  end
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user
  belongs_to :organization, optional: true
  validates :title, presence: true, length: { maximum: 100 }
  validates :description, presence: true
  has_many :wishes, dependent: :destroy
  has_many :integrations, dependent: :destroy

  COLORS = ["ECEDFE", "EFFEEC", "FEFCEC", "FEECEC", "F9ECFE", "ECFEFE"]

  def admin_wishlist?
    status == "admin"
  end

  # rubocop:disable Naming/PredicateName
  def has_an_organization?
    !organization.nil?
  end
  # rubocop:enable Naming/PredicateName

  def self.admin_wishlists
    Wishlist.where(status: "admin")
  end

  def asana_integration
    integrations.find_by(name: "Asana")
  end
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
    add_breadcrumb "home", :authenticated_root_path
    before_action :set_organization, only: [:index]
    skip_before_action :authenticate_user!, only: [:index]

  def index
    @wishlists = policy_scope(@organization.wishlists).includes(:wishes)
  end

  def new
    # @organization = Organization.find(params[:organization]) if params[:organization]
    @organization = current_user.organization
    @wishlist = Wishlist.new
    authorize @wishlist
  end

  def create
    @wishlist = Wishlist.new(wishlist_params)
    @wishlist.user = current_user
    authorize @wishlist
    if @wishlist.save
      flash[:notice] = "Board created successfully"
      redirect_to boards_path
    else
      flash[:alert] = "There was a problem creating your board, try again later: #{@wishlist.errors.full_messages.join(", ")}"
      redirect_to new_wishlist_path
    end
  end

  def destroy
    @wishlist = Wishlist.find(params[:id])
    authorize @wishlist
    if @wishlist.destroy
      flash[:notice] = "Board deleted successfully"
      redirect_to wishlists_path
    else
      flash[:alert] = "Board not deleted, try again later"
      redirect_to wishlist_wishes_path(@wishlist)
    end
  end

  def edit
    @wishlist = Wishlist.find(params[:id])
    authorize @wishlist
  end

  # rubocop:disable Metrics/MethodLength
  def update
    @wishlist = Wishlist.find(params[:id])
    if wishlist_params[:organization_id]
      wishlist_params[:organization_id] =
        current_user.organization.id
    else
      wishlist_params[:organization_id] = nil
    end
    authorize @wishlist
    if @wishlist.update(wishlist_params)
      flash[:notice] = "Board updated successfully"
      redirect_to wishlist_wishes_path(@wishlist)
    else
      flash[:alert] = "There was a problem updating your board, try again later"
      render :edit
    end
  end
  # rubocop:enable Metrics/MethodLength

  private

  def wishlist_params
    params.require(:wishlist).permit(:title, :description, :color, :private, :organization_id)
  end

  def set_organization
    subdomain = request.subdomain
    @organization = Organization.find_by(subdomain:)
    redirect_to authenticated_root_url(subdomain: 'www'), allow_other_host: true unless @organization
  end
end

app/views/wishlists/_form.html.erb
<div data-controller="character-counter">
  <%= simple_form_for @wishlist do |f| %>
      <% if @organization %>
          <%= f.input :organization_id, input_html: { value: @organization.id }, wrapper_html: { class: "d-none" } %>
      <% end %>
      <div class = "character-count">
        <label for="">Insert a descriptiom title</label>
        <span data-target="character-counter.message" class="text-muted"></span>
      </div>
      <%= f.input :title, label: false, required: true, placeholder: "i.e: Product development, Improve wyshlist.net...", maxlength: 100, input_html: { data: { target: "character-counter.input", action: "keyup->character-counter#updateMessage" } } %>
      <%= f.input :description, label: "Summarize the goals of this board", type: :text, placeholder: "i.e: This board is for the product development team..." %>
      <%# Removed private as we are not sure about the logic yet %>
      <%#= f.input :private, label: "Make this board private", input_html: { class: "toggle" } %>
      <%= f.submit "Submit", class: "btn-flat"%>
  <% end %>
</div>

app/views/wishlists/_wishlists_cards.html.erb
<div class="cards">
    <% @wishlists.each do |wishlist| %>
        <%= link_to wishlist_wishes_path(wishlist) do %>
            <div class="card-product">
                <div class="card-product__info">
                    <h2 class="wishlist-title"><%= wishlist.title.truncate(25) %></h2>
                </div>
                <%= wishlist.wishes.count %>
            </div>
        <% end %>
    <% end %>
</div>

app/views/wishlists/edit.html.erb
<div class="my-container">
    <div class="card-product form-wrapper">
        <h1>Edit your board</h1>
       <%= render "form" %>
    </div>
</div>

app/views/wishlists/index.html.erb
<div class="my-container">
    <div class="title-header">
        <div class="title-wrapper">
            <h1><%= t('user_feed.title') %></h1>
            <small><%= t('user_feed.description') %></small>
        </div>
        <% if user_signed_in? && current_user.team_member? %>
          <%= link_to t('user_feed.new_wishlist'), new_wishlist_path, class: "nav-link upvote-button btn-black" %>
        <% end %>
    </div>
    <% if @wishlists.empty? %>
        <div class="card-product">
            <p><%= t('user_feed.no_boards_message') %></p>
            <p><%= t('user_feed.create_one_message') %></p>
        </div>
    <% else %>
        <%= render "wishlists_cards", wishlists: @wishlists %>
    <% end %>
</div>

app/views/wishlists/new.html.erb
<div class="my-container my-5">
    <% if @organization %>
        <h1><%= t('new_board.title_with_org', org_name: current_user.organization.name.capitalize) %></h1>
    <% else %>
        <h1><%= t('new_board.title') %></h1>
    <% end %>
    <p><%= t('new_board.description') %></p>
    <%= render "form" %>
</div>

app/views/wishlists/show.html.erb
<div class="container">
    <div class="title-header">
        <div class="title-wrapper">
            <%= render_breadcrumbs :separator => " / " %>
            <h1> <%= @wishlist.title %></h1>
            <div class="title-main-highlight" style="background-color: #<%= @wishlist.color %>"></div>
            <br>
            <small><%= @wishlist.description %></small>
        </div>
        <div>
        <%= link_to edit_wishlist_path(@wishlist) do %>
            <%= image_tag "edit.png", alt: "edit icon", class: "header-icons" %>
        <% end %>
        <%= link_to wishlist_path(@wishlist), data: {turbo_method: "delete", turbo_confirm: 'Are you sure?'} do %>
            <%= image_tag "trash.png", alt: "edit icon", class: "header-icons" %>
        <% end %>
        </div>
    </div>
    <%= turbo_stream.append 'wishes', partial: "wishlists/wishes", locals: {wishes: @wishes} %>
    <%= turbo_frame_tag "wishes" do %>
        <%= render "wishlists/wishes", wishes: @wishes %>
   <% end %>
    <%= turbo_frame_tag "new-wish" do %>
        <div class="new-wish-wrapper">
            <%= link_to "Add a new idea", new_wishlist_wish_path(@wishlist), class: "btn-flat" %>
        </div>
    <% end %>
</div>